spec:
  configuration:
    maintainer: thibault deheurles <tdeheurles@gmail.com>

    os:   ubuntu:14.04.2

    hive:
      image: tdeheurles/hive
      minor: "5"
      major: "0"

    kubernetes:
      image: tdeheurles/kubernetes
      base: gcr.io/google_containers/hyperkube-amd64

    local_cluster_proxy:
      base: nginx:1.9.7
      image: tdeheurles/local_cluster_proxy
      major: 0
      minor: 0
      name: local_cluster_proxy
