spec:
  configuration:
    maintainer: thibault deheurles <tdeheurles@gmail.com>

    image:
      os:   ubuntu:14.04.2
      hive: tdeheurles/hive

    version:
      hive:
        minor: "5"
        major: "0"
