spec:
  configuration:
    maintainer: thibault deheurles <tdeheurles@gmail.com>

    os:   ubuntu:14.04.2

    hive:
      image: tdeheurles/hive
      minor: "5"
      major: "0"

    kubernetes:
      image: tdeheurles/kubernetes
      base: gcr.io/google_containers/hyperkube
