apiVersion: v1
kind: ReplicationController
metadata:
  name: "<% __SERVICE_NAME__.name %>-<% __SERVICE_NAME__.major %>-<% __SERVICE_NAME__.minor %>-<% cli.id %>"
  labels:
    name: "<% __SERVICE_NAME__.name %>"
    major: "<% __SERVICE_NAME__.major %>"
    minor: "<% __SERVICE_NAME__.minor %>"
    build: "<% cli.id %>"
spec:
  replicas: 1
  selector:
    name: "<% __SERVICE_NAME__.name %>"
    major: "<% __SERVICE_NAME__.major %>"
    minor: "<% __SERVICE_NAME__.minor %>"
    build: "<% cli.id %>"
  template:
    metadata:
      labels:
        name: "<% __SERVICE_NAME__.name %>"
        major: "<% __SERVICE_NAME__.major %>"
        minor: "<% __SERVICE_NAME__.minor %>"
        build: "<% cli.id %>"
    spec:
      containers:
      - name: "<% __SERVICE_NAME__.name %>"
        image: "<% __SERVICE_NAME__.image %>:<% __SERVICE_NAME__.major %>.<% __SERVICE_NAME__.minor %>.<% cli.id %>"
        imagePullPolicy: Always
